local vim = create_vim({ isolate = false })

describe('dir', function()
	test(':edit', function()
		vim.cmd.edit('/')
		assert.is_true(vim.fn.search('./.') == 0)
		assert.is_true(vim.fn.search('^/bin/$') > 0)
		assert.is_true(vim.fn.search('^/etc/$') > vim.fn.search('^/bin/$'))
	end)

	test(':file', function()
		vim.cmd.edit('/')
		assert.is_true(vim.fn.search('^/etc/.*/$') == 0)
		vim.cmd.file('/etc/')
		assert.is_true(vim.fn.search('^/etc/.*/$') > 0)
	end)

	test('filetype', function()
		vim.cmd.edit('/')
		assert.same(vim.o.filetype, 'directory')
	end)

	test('recursive', function()
		vim.cmd.edit('/')
		vim.cmd.file('/etc//')
		assert.same(vim.fn.bufname(), '/etc//')
		assert.is_true(vim.fn.search('^/etc//') == 0)
		assert.is_true(vim.fn.search('^/etc/.*/.') > 0)
	end)
end)

describe('https', function()
	test(':edit', function()
		vim.cmd.edit('https://example.com')
		assert.is_true(vim.fn.search('Example Domain') > 0)
	end)

	test('filetype with no path', function()
		vim.cmd.edit('http://a.c')
		assert.same('', vim.o.filetype)
	end)

	test('filetype with slash path', function()
		vim.cmd.edit('http://a.c/')
		assert.same('', vim.o.filetype)
	end)

	test('filetype with path', function()
		vim.cmd.edit('http://0.0.0.0//a.c')
		assert.same('c', vim.o.filetype)
	end)

	test('filetype with query string', function()
		vim.cmd.edit('http://0.0.0.0/a.json?/a.c')
		assert.same('json', vim.o.filetype)
	end)

	test('filetype with fragment', function()
		vim.cmd.edit('http://0.0.0.0/a.json\\#/a.c')
		assert.same('json', vim.o.filetype)
	end)
end)
