#!/bin/dash
if output=$(
	git diff --staged --stat |
	grep $x ' Bin '
); then
	echo 'Committed binary files:'
	echo '  (use "git rm --cached <file>..." to unstage)'
	printf '%s\n' "$output"
	exit 1
fi
