#!/bin/dash
for x in '-qm1' ''; do
	! git diff --staged --stat | grep $x ' Bin ' \
	&& break || {
		if test -n "$x"; then
			echo 'Committed binary files:'
		else
			echo '(use "git rm --cached <file>..." to unstage)'
			echo
		fi
		false
	}
done
