#!/bin/dash
for x in '-qm1' ''; do
	! git diff --staged | grep --color $x -aiE \
		-e '(token|secret)[a-zA-Z_]*\s*=\s*\S{3,}' \
		-e '(BEGIN|END) RSA PRIVATE KEY' \
		-e '\bAuthorization\s+"?Basic\s+[a-zA-Z0-9+/]+={0,2}' \
		-e '(Access|Secret)\s*(Token|Key)' \
		-e '\b'"$USER"'\b' \
		&& break || {
		if test -n "$x"; then
			echo 'Committed secrets:'
		else
			echo
		fi
		false
	}
done
