#!/bin/dash
if output=$(
	git diff --staged |
	grep --color=always -aiE \
		-e '(token|secret)[a-zA-Z_]*\s*=\s*\S{3,}' \
		-e '(BEGIN|END) RSA PRIVATE KEY' \
		-e '\bAuthorization\s+"?Basic\s+[a-zA-Z0-9+/]+={0,2}' \
		-e '(Access|Secret)\s*(Token|Key)' \
		-e '\b'"$USER"'\b'
); then
	echo 'Committed secrets:'
	echo '  (use "git commit --no-verify" to ignore)'
	printf '%s\n' "$output"
	exit 1
fi
