local vim = create_vim({ isolate = false })

describe('normal mode', function()
	before_each(function()
		vim:set_lines({ 'X-X-O-X-X' })
		vim:feed('4l')
	end)

	test('f', function()
		vim:feed('fXrf')
		vim:assert_lines({ 'X-X-O-f-X' })
		vim:feed(';r;')
		vim:assert_lines({ 'X-X-O-f-;' })
		vim:feed(',r,')
		vim:assert_lines({ 'X-,-O-f-;' })
	end)

	test('F', function()
		vim:feed('FXrF')
		vim:assert_lines({ 'X-F-O-X-X' })
		vim:feed(';r;')
		vim:assert_lines({ ';-F-O-X-X' })
		vim:feed(',r,')
		vim:assert_lines({ ';-F-O-,-X' })
	end)

	test('t', function()
		vim:feed('tXrt')
		vim:assert_lines({ 'X-X-OtX-X' })
		vim:feed(';r;')
		vim:assert_lines({ 'X-X-OtX;X' })
		vim:feed(',r,')
		vim:assert_lines({ 'X-X,OtX;X' })
	end)

	test('T', function()
		vim:feed('TXrT')
		vim:assert_lines({ 'X-XTO-X-X' })
		vim:feed(';r;')
		vim:assert_lines({ 'X;XTO-X-X' })
		vim:feed(',r,')
		vim:assert_lines({ 'X;XTO,X-X' })
	end)
end)

describe('normal mode with count', function()
	before_each(function()
		vim:set_lines({ 'X-X-X-X-X-X-X-X' })
	end)

	test('f', function()
		vim:feed('2fXrf')
		vim:assert_lines({ 'X-X-f-X-X-X-X-X' })
		vim:feed('3;r;')
		vim:assert_lines({ 'X-X-f-X-X-;-X-X' })
		vim:feed('9;r;')
		vim:assert_lines({ 'X-X-f-X-X-;-X-;' })
	end)

	test('F', function()
		vim:feed('$')
		vim:feed('2FXrF')
		vim:assert_lines({ 'X-X-X-X-X-F-X-X' })
		vim:feed('3;r;')
		vim:assert_lines({ 'X-X-;-X-X-F-X-X' })
		vim:feed('9;r;')
		vim:assert_lines({ ';-X-;-X-X-F-X-X' })
	end)
end)

describe('normal mode linewise', function()
	before_each(function()
		vim:set_lines({ 'X', '-O-', 'X' })
		vim:feed('jl')
		vim.o.virtualedit = 'all'
	end)

	test('f', function()
		vim:feed('fXrf')
		vim:assert_lines({ 'X', '-O-', 'f' })
	end)

	test('F', function()
		vim:feed('FXrF')
		vim:assert_lines({ 'F', '-O-', 'X' })
	end)

	test('t', function()
		vim:feed('tXrt')
		vim:assert_lines({ 'X', '-O-t', 'X' })
	end)

	test('T', function()
		vim:feed('TXrT')
		vim:assert_lines({ 'XT', '-O-', 'X' })
	end)
end)

test('normal mode with pattern not found', function()
	vim:set_lines({ 'X-X-X' })
	vim:feed('farf')
	vim:assert_lines({ 'f-X-X' })
end)

describe('visual mode', function()
	before_each(function()
		vim:set_lines({ '|X<--O-->X|' })
		vim:feed('5l')
	end)

	test('f', function()
		vim:feed('vfXd')
		vim:assert_lines({ '|X<--|' })
	end)

	test('F', function()
		vim:feed('vFXd')
		vim:assert_lines({ '|-->X|' })
	end)

	test('t', function()
		vim:feed('vtXd')
		vim:assert_lines({ '|X<--X|' })
	end)

	test('T', function()
		vim:feed('vTXd')
		vim:assert_lines({ '|X-->X|' })
	end)
end)

describe('operator-pending mode', function()
	before_each(function()
		vim:set_lines({ 'X', 'X<--O-->X', 'X' })
		vim:feed('j4l')
	end)

	test('f', function()
		vim:feed('dfX')
		vim:assert_lines({ 'X', 'X<--', 'X' })
		vim:feed('.')
		vim:assert_lines({ 'X', 'X<-' })
	end)

	test('F', function()
		vim:feed('dFX')
		vim:assert_lines({ 'X', 'O-->X', 'X' })
		vim:feed('.')
		vim:assert_lines({ 'O-->X', 'X' })
	end)

	test('t', function()
		vim.o.virtualedit = 'all'
		vim:feed('dtX')
		vim:assert_lines({ 'X', 'X<--X', 'X' })
		vim:feed('.')
		pending('Likely unfixable')
		vim:assert_lines({ 'X', 'X<--X' })
	end)

	test('T', function()
		vim:feed('dTX')
		vim:assert_lines({ 'X', 'XO-->X', 'X' })
		vim:feed('.')
		pending('Likely unfixable')
		vim:assert_lines({ 'XO-->X', 'X' })
	end)
end)

describe('f with character', function()
	local function case(c)
		describe(c, function()
			test('stops anywhere', function()
				vim:set_lines({ 'xxx' .. c .. 'xxx' })
				vim:feed('f' .. c .. 'rf')
				vim:assert_lines({ 'xxxfxxx' })
			end)
		end)
	end

	case("'")
	case(' ')
	case('"')
	case('$')
	case('(')
	case(')')
	case('*')
	case('+')
	case('-')
	case('.')
	case('0')
	case('3')
	case('6')
	case('9')
	case('>')
	case('?')
	case('A')
	case('J')
	case('R')
	case('Z')
	case('[')
	case('\\')
	case(']')
	case('^')
	case('{')
	case('}')
end)

describe('f with lower-case character', function()
	local function case_helper(c, name, input, expected)
		local function sub(s)
			return (s:gsub('[a]', c):gsub('A', string.upper(c)))
		end

		test(string.format('%s stops %s', c, name), function()
			vim:set_lines({ sub(input) })
			vim:feed('f' .. c .. 'r|')
			vim:assert_lines({ sub(expected) })
		end)
	end

	local function case(...)
		case_helper('a', ...)
		case_helper('j', ...)
		case_helper('r', ...)
		case_helper('z', ...)
	end

	case('inside snake_case word', 'xaaa_aaaa', 'xaaa_|aaa')
	case('inside kebab-case word', 'xaaa-aaaa', 'xaaa-|aaa')
	case('inside SCREAMING_SNAKE_CASE word', 'XXX_AAA', 'XXX_|AA')
	case('inside CamelCase word', 'XaaaAaaa', 'Xaaa|aaa')
	case('inside UPPERCASE word', 'XXXAAA', 'XXX|AA')
	case('after digit 0', 'x0ax', 'x0|x')
	case('after digit 3', 'x3ax', 'x3|x')
	case('after digit 6', 'x6ax', 'x6|x')
	case('after digit 9', 'x9ax', 'x9|x')
end)
