local vim = create_vim()

test(':Register', function()
	vim.fn.setreg('x', 'aaa\naaa')
	vim.cmd.Register('x')
	vim:assert_lines({ 'aaa', 'aaa' })
end)

test(':edit', function()
	vim.cmd.Register('x')
	vim.fn.setreg('x', 'bbb\nbbb')
	vim.cmd.edit()
	vim:assert_lines({ 'bbb', 'bbb' })
end)

test(':write', function()
	vim.cmd.Register('x')
	vim:set_lines({ 'ccc', 'ccc' })
	vim.cmd.write()
	assert.are.same(vim.fn.getreg('x'), 'ccc\nccc\n')
end)
