local vim = create_vim()

test(':Register', function()
	vim.fn.setreg('x', 'a\n\nb\n')
	vim.cmd.Register('x')
	vim:assert_lines({ 'a', '', 'b', '' })
end)

test(':edit', function()
	vim.cmd.Register('x')
	vim.fn.setreg('x', 'a\n\nb\n')
	vim.cmd.edit()
	vim:assert_lines({ 'a', '', 'b', '' })
end)

test(':write', function()
	vim.cmd.Register('x')
	vim:set_lines({ 'a', '', 'b', '' })
	vim.cmd.write()
	assert.same('a\n\nb\n', vim.fn.getreg('x'))
end)
