SPACE	cycle pause
c	cycle pause
MBTN_RIGHT	cycle pause
o	script-message osd-bar visibility blink
O	script-message osd-bar visibility toggle

V	cycle video
A	cycle_values video-aspect-override 16:9 no
S	cycle sub-visibility
t	script-message select-track

m	cycle mute
MBTN_LEFT	cycle mute
Ctrl+a	script-message choose-audio-device visibility toggle

<	sub-step -1
>	sub-step +1

z	script-message audio-delay
Z	set audio-delay 0

+	add volume +1
-	add volume -2
=	set volume 100

x	playlist-remove current
p	script-binding playlist-prev
P	script-binding playlist-next
n	script-binding playlist-next
N	script-binding playlist-prev
r	script-binding playlist-random
Ctrl+d	script-message osd-playlist scroll-half-screen down
Ctrl+u	script-message osd-playlist scroll-half-screen up
Ctrl+o	script-message playlist-older
w	show_text "[${playlist-pos}/${playlist-count}] ${metadata/by-key/Title:${media-title:${filename}}}"; script-message osd-playlist visibility peek
W	script-message osd-playlist visibility toggle
G	script-message playlist-pos 0

[	multiply speed 1/1.1
]	multiply speed 1.1
*	script-binding push-to-fastforward

u	script-message osd-colors visibility toggle
{	script-message osd-colors preset prev
}	script-message osd-colors preset next

,	frame-back-step
;	frame-step

g	repeatable script-message osd-bar seek 0 absolute
e	no-osd seek +1.5 exact
b	no-osd seek -1 exact
h	no-osd seek -3
l	repeatable script-message osd-bar seek +3
j	repeatable script-message osd-bar seek -30 keyframes
k	repeatable script-message osd-bar seek +30 keyframes
J	repeatable script-message osd-bar seek -120 keyframes
K	repeatable script-message osd-bar seek +120 keyframes
Right	repeatable script-message osd-bar seek +1
Left	repeatable script-message osd-bar seek -1
Down	repeatable script-message osd-bar seek -10
Up	repeatable script-message osd-bar seek +10

L	ab-loop
F	cycle-values loop-file no inf

i	script-binding stats/display-stats
I	script-binding stats/display-stats-toggle
:	script-binding console/enable
`	script-binding console/enable; script-message-to console type "script-message "

B	script-message imdb
C	script-message osd-cache visibility toggle
Ctrl+r	script-binding reload-file
DEL	script-binding delete-file
H	script-message hup toggle
M	script-message osd-metadata visibility toggle
R	screenshot
T	script-message osd-title visibility toggle
U	script-message tv visibility toggle
f	script-message select-filters
y	script-message yank-title

q	script-message confirm-if "(demuxer_cache_duration or 0) > 600 or demuxer_via_network" quit
Ctrl+c	quit 3

!	script-message mpt-start-tmux
/	script-message mpt-if "script-message mpt select-playlist" "script-message select-playlist"
Ctrl+w	script-message mpt edit-playlist
Ctrl+p	script-message mpt edit-properties
# vim:set ft=conf ts=15:
