#!/bin/sh
file='.aria2cd.conf.cmdline'
router='-u http://10.0.0.1:5000/rootDesc.xml'
desc='BitTorrent'

dht_port=$(awk -F= '$1=="--dht-listen-port"{print $2;exit}' "$file" 2>/dev/null)
listen_port=$(awk -F= '$1=="--listen-port"{print $2;exit}' "$file" 2>/dev/null)

case "${1:-start}" in
start)
  random_port() {
    seq 10000 65535 | shuf -n1
  }

  test -n "$dht_port" || dht_port=$(random_port)
  test -n "$listen_port" || listen_port=$(random_port)
  external_ip=$(
    upnpc -e "$desc" $router -r "$dht_port" udp "$listen_port" tcp |
    awk -F' = ' '$1=="ExternalIPAddress"{print $2;exit}'
  )
  if test -n "$external_ip"; then
    cat >"$file" <<EOF
--bt-external-ip=$external_ip
--enable-dht=true
--dht-listen-port=$dht_port
--listen-port=$listen_port
EOF
    echo "External IP: $external_ip."
    echo "Opened ports: $dht_port/udp, $listen_port/tcp."
  else
    cat >"$file" <<EOF
--enable-dht=false
--enable-dht6=false
EOF
    echo >&2 "Failed to open ports: $dht_port/udp, $listen_port/tcp."
    test ! -f "$file"
  fi
  ;;

stop)
  if test -n "$dht_port"; then
    upnpc >/dev/null $router -d "$dht_port" udp ||
    echo >&2 "Failed to close port: $dht_port/udp."
  fi

  if test -n "$listen_port"; then
    upnpc >/dev/null $router -d "$listen_port" tcp ||
    echo >&2 "Failed to close port: $listen_port/tcp."
  fi
  unlink "$file" 2>/dev/null
  :
  ;;

*)
  echo >&2 "Unknown command: $1."
  exit 2
  ;;
esac
