#!/usr/bin/dash
# http://paletton.com/#uid=12l0u0kg8YS2a+Zas+tk-Uzn-J6
playerctl metadata -F --format "{{ status }} {{ volume }} {{ artist }} — {{ title }}" |
while read status volume playing; do
  playing=$(echo "$playing" | sed 's_&_&amp;_g; s_<_&lt;_g; s_>_&gt;_g; s#^—# <i>ID</i> —#; s#—$#— <i>ID</i>#')
  case "$status" in
  Playing) status="<span color='#ffee7e'> " ;;
  Paused)  status="<span color='#d5fe7e'> " ;;
  Stopped) status="<span color='#d5fe7e'> " ;;
  *)       status="<span>$status: " ;;
  esac
  if [ "$volume" == "1.0" ]; then
    volume=
  else
    volume="$(echo "scale=0; $volume*100/1" | bc)% "
  fi

  echo "<span color='#ff7e7e'> $volume</span>$status$playing</span>"
done
