#!/usr/bin/dash
# 糖
# http://paletton.com/#uid=1180u0kqvuqj9LAmTAFsjnKukg5
sensors | awk '
function to_c(p) {
  p=substr(p,2,length(p)-5)
  return p "°C"
}
/^CPU:/     { cpu_temp = $2 }
/^SODIMM:/  { mem_temp = $2 }
/^Ambient:/ { env_temp = $2 }
END {
  print "" \
  "  " to_c(cpu_temp) \
  "  " to_c(mem_temp) \
  " 滑 " to_c(env_temp)
  print "" \
  "  " to_c(cpu_temp)
}'
# <span color=\"#fe757c\">
# <span color=\"#f4a453\">
# <span color=\"#73A461\">
