#!/bin/dash -eu
target=$(
	tmux list-panes -a -F "$(printf '#{pane_id}\t#{session_name}:#{window_name}:#{window_flags}\t#{pane_title}')" |
	fizzy -aj0 |
	cut -f1
)
test -n "$target"
tmux switch-client -t "$target"
