require('choose-value')
require('osd-bar')
require('osd-cache')
require('osd-colors')
require('osd-filters')
require('osd-icons')
require('osd-metadata')
require('osd-playlist')
require('osd-title')
require('osd-tracks')
require('yank-title')

assert(mp.flush_keybindings)
mp.unregister_idle(mp.flush_keybindings)
