#!/bin/sh -eux
test_case() {
	test_name=${1?}

	actual=$test_name.actual
	expected=$test_name.expected

	script -c "./init.lua ${2?}; echo exit \$?" "$actual"
	sed -i '1d;$d' "$actual"

	test -f "$expected" || cp -- "$actual" "$expected"

	diff -su "$actual" "$expected"

	rm -- "$actual"
}

test_case 1-basic ''
test_case 2-unknown_arg '-z'
test_case 3-arg_g "-g '**/empty*'"
test_case 4-arg_p "-p 'par.*eters$'"
test_case 5-arg_s "-s"
