#!/bin/zsh -eu
. $ZDOTDIR/hashes.zsh

[[ -d ~V ]] && dir='~V' || dir='~m'

printf '%s\n dir='$dir'\n' ~m/*.torrent >$2
$EDITOR $2
while IFS= read -r line; do
	if [[ $line =~ '^(\s+dir=)(.*)$' ]]; then
		# tilde expand
		eval dir=$match[2]
		line=$match[1]$dir
	fi
	print $line
done <$2 |
sponge $2
