#!/usr/bin/env python3
import aria2t
import signal, os, subprocess
from shlex import join
import xmlrpc.client

signal.signal(signal.SIGTTOU, signal.SIG_IGN)
signal.signal(signal.SIGTTIN, signal.SIG_IGN)

r = aria2t.s.aria2.tellStatus(aria2t.token, aria2t.gid, ['bittorrent', 'files', 'dir'])
if r.get('bittorrent', {}).get('mode', 'single') == 'multi':
	files = [os.path.join(r['dir'], r['bittorrent']['info']['name'])]
else:
	files = [f['path'] for f in r['files']]

subprocess.run([os.environ.get('SHELL', 'sh'), "-ic", 'ls -r %s' % join(files), 'command'])

os.tcsetpgrp(2, os.getpgrp())

reply = input('Are you sure you want to remove this download? [y/N/d] ')
if reply in ['y', 'Y', 'd', 'D']:
	try:
		aria2t.s.aria2.remove(aria2t.token, aria2t.gid)
	except:
		pass

	if reply in ['d', 'D']:
		subprocess.run(["rm", "-rv", *files])
