#!/bin/sh

kill_neomutt() { kill $ppid; }

trap kill_neomutt HUP INT TERM

# get parent pid without padding
ppid=$(ps -p $$ -o ppid= | tr -d \ )

# Checking if we are running under Tor
if curl -s "https://check.torproject.org" | grep "Sorry. You are not using Tor."; then
  echo -e "\e[31mfailed.\e[0m" > /dev/tty
  kill_neomutt
# else
#   echo -e "\e[32mok.\e[0m" > /dev/tty
fi
