#!/bin/sh
echo # newline needed
/usr/bin/abook \
  --outformatstr='{email}\t{name}\t{nick}' \
  --convert \
  --outformat=custom < ~/.config/abook/addressbook |
awk -F\\t -vOFS=\\t '
{
  split($1, a, ",");
  for(i in a)
    print a[i], $2, $3
}' |
grep -i "$1"
