#!/bin/dash
if [ $1 -gt 0 -a $2 -gt 0 ]; then
	$(
		if [ -n "$DISPLAY" ]; then
			echo i3-nagbar
		elif [ -n "$WAYLAND_DISPLAY" ]; then
			echo swaynag
		fi
	) -t warning -m "$1 new messages, $2 unread" >/dev/null 2>/dev/null
fi
