#!/usr/bin/dash
eval $(xdotool getmouselocation --shell)

eval $(xdotool getmouselocation --shell)
CENTER_X=$X
CENTER_Y=$Y

ROOT_WIN=$(xdotool search --maxdepth 0 --screen "$SCREEN" --name '.*')
eval $(xdotool getactivewindow getwindowgeometry --shell "$ROOT_WIN")

LEFT=$X
RIGHT=$((X + WIDTH))
TOP=$Y
BOTTOM=$((Y + HEIGHT))

KEYBOARD_NAME=$(xinput list --name-only | awk '/Keyboard/ {print $0; exit}')

KEY_SPACE=65
KEY_ESC=66
KEY_J=54
KEY_K=55
KEY_H=44
KEY_L=33

xinput test "$KEYBOARD_NAME" |
while read -r keylit state keyid; do
  if [ "press" = "$state" ]; then
    case "$keyid" in
    $KEY_SPACE) xdotool click 1; exit ;;
    $KEY_ESC) exit ;;
    # down
    $KEY_J) TOP=$CENTER_Y; CENTER_Y=$(( (TOP + BOTTOM) / 2 )); ;;
    # up
    $KEY_K) BOTTOM=$CENTER_Y; CENTER_Y=$(( (TOP + BOTTOM) / 2 )); ;;
    # left
    $KEY_H) RIGHT=$CENTER_X; CENTER_X=$(( (LEFT + RIGHT) / 2 )); ;;
    # right
    $KEY_L) LEFT=$CENTER_X; CENTER_X=$(( (LEFT + RIGHT) / 2 )); ;;
    esac

    xdotool mousemove $CENTER_X $CENTER_Y
  fi

done
