#!/usr/bin/dash
xinput list --name-only |
grep -i -e 'touchpad$' -e 'stick$' |
while read -r device; do
	xinput $(case "$1" in
		toggle)
			xinput --list-props "$device" |
			awk '/Device Enabled/ {
				print $4 ? "disable" : "enable";
				exit
			}'
			;;
		*)
			echo -n "$1"
			;;
	esac) "$device"
done
