#!/usr/bin/env python3
from base64 import b64encode
from xml.etree.cElementTree import Element, ElementTree, SubElement
import html
import json
import sys
import urllib.request
import os

URL = "https://api.github.com/notifications"
USERNAME = os.environ["GITHUB_USERNAME"]
PASSWORD = os.environ["GITHUB_PASSWORD"]

credential = b64encode(f"{USERNAME}:{PASSWORD}".encode()).decode()

data = json.loads(
    urllib.request.urlopen(
        urllib.request.Request(
            URL,
            headers={
                "Authorization": f"Basic {credential}",
            },
        ),
    ).read()
)

feed = Element("feed")
SubElement(feed, "title").text = "GitHub - Notifications"
SubElement(feed, "id").text = URL
SubElement(
    feed,
    "link",
    rel="alternate",
    type="text/html",
    href="https://github.com/notifications",
)

for item in data:
    entry = SubElement(feed, "entry")
    SubElement(entry, "id").text = item["id"]
    SubElement(entry, "updated").text = item["updated_at"]
    SubElement(
        entry,
        "link",
        rel="alternate",
        type="text/html",
        href=item["subject"]["url"],
    )
    SubElement(entry, "title").text = html.unescape(
        "%s: %s" % (item["repository"]["name"], item["subject"]["title"])
    )
    SubElement(entry, "summary").text = ""

ElementTree(feed).write(
    sys.stdout.buffer,
    encoding="utf-8",
    xml_declaration=True,
)
