#!/usr/bin/python
from datetime import datetime
from xml.etree.ElementTree import Element, ElementTree, SubElement
import html
import re
import sys
import urllib.request

URL = "https://portal.nebih.gov.hu/termekvisszahivas"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"

ENTRY_RE = (
    r'<td class="col"> (?P<date>[^<]*)</td>\s*'
    + r'<td class="col"> (?P<name>[^<]*)</td>\s*'
    + r'<td class="col"> (?P<reason>[^<]*)</td>\s*'
    + r'<td class="col">.*?(?P<id>\d+)">'
)

request = urllib.request.Request(
    URL,
    headers={"User-Agent": USER_AGENT},
)
text = urllib.request.urlopen(request).read().decode("utf-8")

rss = Element("rss", version="2.0")
channel = SubElement(rss, "channel")
SubElement(channel, "language").text = "hu"
SubElement(channel, "title").text = "Nébih - Termékvisszahívás"
SubElement(channel, "link").text = URL

for entry in re.finditer(ENTRY_RE, text):
    item = SubElement(channel, "item")
    SubElement(item, "pubDate").text = datetime.strptime(
        entry["date"], "%Y.%m.%d."
    ).date().isoformat()
    SubElement(item, "title").text = html.unescape(html.unescape(entry["name"]))
    SubElement(
        item, "guid", isPermaLink="true"
    ).text = f"https://portal.nebih.gov.hu/l/termekvisszahivas/{entry['id']}"
    SubElement(item, "description").text = entry["reason"]

ElementTree(rss).write(
    sys.stdout.buffer,
    encoding="utf-8",
    xml_declaration=True,
)
