#!/bin/dash -e
f=${TMPDIR:-/tmp}/mutt-compose.$$
trap 'rm -- "$f"' EXIT INT KILL QUIT
mkfifo "$f"
tmux -N new-window -a dash -c 'exec 3>$1 && shift; "$@"; echo $?>&3' sh "$f" "${EDITOR?}" "$@"
read code <"$f"
exit "${code:-127}"
