#!/usr/bin/env python
from urllist import URLList
import re

class MyURLList(URLList):
	@classmethod
	def map(cls, url):
		return re.sub(r'\.gifv$', '.mp4', url)

print(*MyURLList.from_mail(), sep='\n', end='')
