#!/usr/bin/dash -eu
trap 'exit 0' INT TERM QUIT

url=$(
	${0%/*}/urllist |
	fizzy -1
)

for action; do
	case $action in
	open)
		if pidof firefox >/dev/null; then
			firefox "$url" >/dev/null 2>/dev/null &
			return
		fi
		;;

	copy)
		printf %s "$url" |
		{
			xclip -i -selection clipboard ||
			tmux load-buffer -
		} &&
		return
		;;

	*)
		printf >&2 'unknown action: %s' "$action"
		return 1
		;;
	esac
done
