#!/usr/bin/python
from urllist import URLList
from subprocess import check_output, run, Popen, CalledProcessError, DEVNULL
import re


class MyURLList(URLList):
    @classmethod
    def map(cls, url):
        return re.sub(r"\.gifv$", ".mp4", url)


try:
    url = check_output(
        ["fzr", "-1"], input="\n".join(MyURLList.from_mail()).encode("utf-8")
    )
except CalledProcessError:
    pass
except KeyboardInterrupt:
    pass
else:

    def is_running(cmd):
        try:
            run(
                ["pidof", cmd],
                stdin=DEVNULL,
                stdout=DEVNULL,
                stderr=DEVNULL,
                check=True,
            )
            return True
        except CalledProcessError:
            return False

    import sys

    for action in sys.argv:
        match action:
            case "open":
                if is_running("firefox"):
                    import shlex
                    Popen(
                        shlex.join(["firefox", url.decode('utf-8')]),
                        shell=True,
                        stdin=DEVNULL,
                    )
                    break
            case "copy":
                run(
                    ["xclip", "-i", "-silent", "-selection", "clipboard"],
                    input=url,
                )
                break
