#!/bin/dash
set -e
while [ $# -ge 2 ]; do
  readonly cmus_$1="$2"
  shift
  shift
done

# http://www.1x1px.me/
cd $XDG_RUNTIME_DIR
if [ ! "$(readlink cmus-current)" = "$cmus_file" ]; then
  ln -sf "$cmus_file" cmus-current
  index=$(ffprobe cmus-current -hide_banner -loglevel quiet -show_streams -select_streams v |
    awk -F= 'BEGIN {i=-1} $1=="index" {i=$2} $1=="TAG:comment" && $2~/[Cc]over/ {exit} END {print i}')
  ffmpeg -hide_banner -loglevel quiet -y -i cmus-current -map "0:$index" -c copy cmus-cover.out.jpg &&
  mv -f cmus-cover.out.jpg cmus-cover ||
  cp -f ~/.config/cmus/default-cover cmus-cover
  # truncate -s 0 cmus-cover
fi
