#!/bin/zsh
setopt nohup
zmodload zsh/terminfo

echoti clear
echoti rmam # no line wrap
echoti civis # hide cursor

for i in {1..8}; echo # status line
lsblk -o NAME,LABEL,FSAVAIL,FSUSE%
echo
cal -mw

echoti home
seabar &
pid=$!

while read -rk1; do
	kill "$pid"

	echoti clear

	case $REPLY in
	b) exec setsid -f firefox ;;
	t) exec setsid -f telegram-desktop ;;
	p) exec top ;;
	o) exec progress -M ;;
	m) exec neomutt ;;
	a) exec aria2t ;;
	s) exec /bin/kill -SIGSTOP $(pidof firefox) ;;
	c) exec /bin/kill -SIGCONT $(pidof firefox) ;;

	d) exec magixrandr switch dual ;;
	h) exec magixrandr switch home ;;
	l) exec magixrandr switch laptop ;;
	x) magixrandr switch off ;;

	S) exec setsid -f ${0%/*}/screenshit ;;
	*) exit
	esac
done
