#!/bin/zsh
setopt nohup
zmodload zsh/terminfo

echoti clear
echoti rmam # no line wrap
echoti civis # hide cursor

echo # status line
lsblk -o NAME,LABEL,FSAVAIL,FSUSE%
echo
cal -mw

echoti home
~/pro/seabar/seabar &
pid=$!

read -rk1

kill $pid

echoti clear

case $REPLY in
b) exec setsid -f firefox ;;
t) exec setsid -f telegram-desktop ;;
m) exec neomutt ;;
a) exec aria2t ;;
s) exec /bin/kill -SIGSTOP $(pidof firefox) ;;
c) exec /bin/kill -SIGCONT $(pidof firefox) ;;

d) exec magixrandr switch dual ;;
h) exec magixrandr switch home ;;
l) exec magixrandr switch laptop ;;
esac
