#!/bin/zsh -eu
. $ZDOTDIR/hashes.zsh

while IFS= read -r line; do
	if [[ $line =~ '^(instance=)(~.*)$' ]]; then
		# tilde expand
		eval dir=$match[2]
		line=$match[1]$dir
	fi
	print $line
done <config.in >config
